VERSION: 2
#model: deit_tiny_patch16_224
model_cfg:
  type: CPVT
  kwargs:
    patch_size: 16
    embed_dim: 192
    depth: 12
    num_heads: 3
    pretrained: false
    num_classes: 1000
    drop_rate: 0.
    drop_path_rate: 0.1
    cpe_idx: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11
batch_size: 512