VERSION: 2
#model: deit_tiny_patch16_224
model_cfg:
  type: RecurrentVisionTransformer
  kwargs:
    patch_size: 16
    embed_dim: 384
    depth: 1
    inner_recurrence: 12
    outer_recurrence: 1
    num_heads: 6
    pretrained: deit_tiny_d1.pth
    num_classes: 1000
    drop_rate: 0.
    drop_path_rate: 0.1
batch_size: 256